# Generated by Django 3.1.2 on 2020-10-25 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20201025_0829'),
        ('users', '0002_auto_20200914_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.organization'),
        ),
    ]
