# Generated by Django 3.1.1 on 2020-09-27 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='purchaseentry',
            options={'verbose_name_plural': 'Purchase Entries'},
        ),
    ]
