# Generated by Django 3.1.1 on 2020-09-28 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_auto_20200928_0513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseinvoice',
            options={'verbose_name_plural': 'Purchase Invoices'},
        ),
        migrations.RenameField(
            model_name='purchaseinvoiceentry',
            old_name='purchase',
            new_name='invoice',
        ),
    ]
