# Generated by Django 3.1.1 on 2020-09-18 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_auto_20200916_1308'),
        ('organization', '0004_auto_20200914_0713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='organization.organization')),
                ('products', models.ManyToManyField(limit_choices_to={'organization': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='organization.organization')}, related_name='in_invoices', to='products.Product')),
            ],
        ),
    ]
