# Generated by Django 3.1.1 on 2020-09-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_squashed_0006_remove_invoiceentry_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceentry',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(),
        ),
    ]
