# Generated by Django 3.1.1 on 2020-09-18 13:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20200918_0938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceentry',
            options={'verbose_name_plural': 'Invoice Entries'},
        ),
        migrations.AddField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 18, 13, 48, 14, 753274, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
