# Generated by Django 3.1.1 on 2020-09-20 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20200918_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceentry',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='sales.invoice'),
        ),
    ]
