# Generated by Django 3.1.1 on 2020-09-23 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_minimum_price'),
        ('sales', '0004_auto_20200923_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceentry',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_invoices', to='products.product'),
        ),
    ]
