# Generated by Django 3.1.1 on 2020-09-24 05:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20200923_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 24, 5, 27, 34, 364225, tzinfo=utc)),
        ),
    ]
