# Generated by Django 3.1.1 on 2020-09-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20200924_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[(0, 'Pending'), (1, 'Completed')], default=0, max_length=20),
        ),
    ]
