# Generated by Django 3.1.1 on 2020-09-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.BooleanField(choices=[('Pending', 0), ('Completed', 1)], default=0, max_length=20),
        ),
    ]
