# Generated by Django 3.1.1 on 2020-09-24 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_auto_20200924_0826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='status',
            new_name='completed',
        ),
    ]
