# Generated by Django 3.1.1 on 2020-09-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_auto_20200924_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='completed',
        ),
        migrations.AddField(
            model_name='invoice',
            name='finalized',
            field=models.BooleanField(choices=[(0, 'Pending'), (1, 'Finalized')], default=0, max_length=20),
        ),
    ]
