# Generated by Django 3.1.1 on 2020-09-27 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20200914_0713'),
        ('products', '0003_product_minimum_price'),
        ('sales', '0014_auto_20200927_1330'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalesInvoice',
            new_name='Invoice',
        ),
        migrations.RenameModel(
            old_name='SalesInvoiceEntry',
            new_name='InvoiceEntry',
        ),
        migrations.AlterModelOptions(
            name='invoiceentry',
            options={'verbose_name_plural': 'Invoice Entries'},
        ),
    ]
