# Generated by Django 3.1.1 on 2020-09-27 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_minimum_price'),
        ('organization', '0004_auto_20200914_0713'),
        ('sales', '0015_auto_20200927_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('finalized', models.BooleanField(choices=[(0, 'Pending'), (1, 'Finalized')], default=0, max_length=20)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesinvoice', to='organization.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='sales.salesinvoice')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salesinvoiceentry', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Sales Invoice Entries',
            },
        ),
        migrations.RemoveField(
            model_name='invoiceentry',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceentry',
            name='product',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceEntry',
        ),
    ]
