# Generated by Django 3.1.1 on 2020-09-28 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_auto_20200927_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesinvoice',
            options={'ordering': ['-id']},
        ),
    ]
