# Generated by Django 3.1.1 on 2020-09-23 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('products', '0001_initial'), ('products', '0002_auto_20200914_1025'), ('products', '0003_auto_20200914_1028'), ('products', '0004_product_brand'), ('products', '0005_auto_20200916_1031'), ('products', '0006_auto_20200916_1120'), ('products', '0007_auto_20200916_1308'), ('products', '0008_auto_20200923_0437')]

    initial = True

    dependencies = [
        ('organization', '0004_auto_20200914_0713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=12)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='organization.organization')),
                ('category', models.CharField(blank=True, default=' ', max_length=255)),
                ('brand', models.CharField(blank=True, default=' ', max_length=255)),
                ('unit', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'order_with_respect_to': 'organization',
            },
        ),
    ]
