# Generated by Django 3.1.1 on 2020-09-14 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200914_1025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='category',
            order_with_respect_to='organization',
        ),
        migrations.AlterOrderWithRespectTo(
            name='product',
            order_with_respect_to='organization',
        ),
    ]
