# Generated by Django 3.1.1 on 2020-09-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200923_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimum_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
