# Generated by Django 3.1.1 on 2020-09-16 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20200914_0713'),
        ('products', '0004_product_brand'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('organization',), ('code',)},
        ),
    ]
