# Generated by Django 3.1.1 on 2020-09-16 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20200914_0713'),
        ('products', '0005_auto_20200916_1031'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('organization', 'code')},
        ),
    ]
